from typing import Any, AsyncContextManager, Protocol


class DatabaseProtocol(Protocol):
    async def execute(self, query: str, *args: Any) -> str: ...
    async def fetch(self, query: str, *args: Any) -> list[Any]: ...
    async def fetchrow(self, query: str, *args: Any) -> Any: ...
    async def fetchval(self, query: str, *args: Any) -> Any: ...
    async def execute_script(self, script: str) -> None: ...
    async def transaction(self) -> AsyncContextManager[Any]: ...
